version: '3.8'

services:
  postgres_test:
    image: postgres:13
    container_name: av2-software-quality-db-test
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: av2-software-quality-test
    ports:
      - "5433:5432"
    networks:
      - db_network
networks:
  db_network:
    driver: bridge
