version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: av2-software-quality-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: av2-software-quality
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - db_network

networks:
  db_network:
    driver: bridge
